### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by Menkir** [kpcyrd/badtouch#54]
Hello @kpcyrd. Im currently searching a crate where i can something contribute. As i see, there are 2 contributors on this project, so do you work as a team only or can i contribute as well?

**Comment by kpcyrd** [comment]
hey @Menkir :) pullrequests are very welcome! Feel free to create an issue first if you are unsure if your feature would get accepted or if you run into issues, the internals are still a bit lightly documented.
