### ISSUE TITLE
failed to run custom build command for `openssl v0.9.24`

### ISSUE THREAD

**Issue by jJit0** [kpcyrd/badtouch#70]
Hi,

I have this error when I install badtouch in cargo: cargo install badtouch

error: failed to run custom build command for `openssl v0.9.24`
process didn't exit successfully: `/tmp/user/0/cargo-installenmH0c/release/build/openssl-1a53f5853bfeae35/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /usr/cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: Run with `RUST_BACKTRACE=1` for a backtrace.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `badtouch v0.6.1`, intermediate artifacts can be found at `/tmp/user/0/cargo-installenmH0c`
Caused by:
  build failed

I have by the way, the latest version of openssl installed v1.1.1b

**Comment by kpcyrd** [comment]
Thanks for pointing this out, I've pushed a new release that resolves this issue.
