### ISSUE TITLE
Outdated Cargo.lock file?

### ISSUE THREAD

**Issue by carlocab** [kpcyrd/badtouch#76]
badtouch is currently failing to build for Homebrew with Rust 1.49 on Apple Silicon: https://github.com/Homebrew/homebrew-core/pull/68089

It appears this is due to a stale lock file, causing `cargo install --locked` to pull in dependencies that do not work for badtouch on Apple Silicon. Is it possible for the `Cargo.lock` file to be updated? If this could be done with a new release, that would be especially helpful.

Related: https://github.com/Homebrew/homebrew-core/issues/68301

**Comment by kpcyrd** [comment]
Sorry for the delay, I've published a new version as [v0.7.2](https://github.com/kpcyrd/badtouch/releases/tag/v0.7.2)!

**Comment by carlocab** [comment]
Thanks! ARM build succeeded: https://github.com/Homebrew/homebrew-core/pull/68806/checks?check_run_id=1683288267

**Comment by kpcyrd** [comment]
Cool, thanks! It seems there's an issue with the 10.15 and 10.14 builds because I changed the ulimit code from `#[cfg(target_os="linux")]` to `#[cfg(unix)]`. Should I do another release that disables them on OSX again until they are working properly?

**Comment by carlocab** [comment]
Thank you for checking on the build! I had a quick look at the errors but haven't really had the time to diagnose them properly.

The solution you propose sounds like the simplest way to get around the build error, so I'm happy with it if you are.

**Comment by kpcyrd** [comment]
Sorry for the inconvenience, this has been fixed in 0.7.3.

Thanks for your work!
